# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0dd35420c4bbaff73b350bd8dd1dfd6b39f35e4bf69e3c9831e6597aad9dfc85538dc7c9c9c7a2545a2e2542667a836f85fe9234a3b037253879fdd6aa73303

test:
  secret_key_base: a2de0714dfe21f33e91b7f734265db7cc230834d25a32eda0784c7795ab6eb73d5cc46be2dbda1cdaaf7bebec048ad741b718568a6d38f3012df7956f7913df3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
